# USB-boot GRUB config — per-stick, generated by flash-usb.sh.
# Differs from the PXE grub.cfg in two ways:
#   1. The provisioning server's IP:port is baked in (no TFTP / proxy DHCP).
#   2. The target's hostname is baked into the kernel cmdline, so the
#      installer can fetch credentials by name (no MAC watcher needed).
#
# The installer reads viam_hostname=... from /proc/cmdline in late-commands.

set timeout=3
set default=autoinstall

menuentry "Viam Provisioning Install (${MACHINE_NAME})" --id=autoinstall {
    linux /vmlinuz ip=dhcp url=http://${PXE_SERVER}/ubuntu/ubuntu-24.04.4-live-server-amd64.iso autoinstall ds=nocloud-net\;s=http://${PXE_SERVER}/autoinstall/ viam_hostname=${MACHINE_NAME} nomodeset vga=791 quiet ---
    initrd /initrd
}

menuentry "Reboot" {
    reboot
}

menuentry "Shut down" {
    halt
}
